// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/22/2024, 12:05:18 PM
const configMerger = require("/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/plugins/**/*.{js,ts,mjs}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/composables/**/*.{js,ts,mjs}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/utils/**/*.{js,ts,mjs}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/mobo/Desktop/BlogPostFullStack/Frontend_Nuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
